### PR TITLE
refactor: improve regex and refactor

### PR DESCRIPTION
**Pull request by Borrus-sudo**

### CODE REVIEW

**Comment by Borrus-sudo** [comment]
The new regex should allow your braces to stretch to multiple lines

**Comment by bharadwajduggaraju** [comment]
This PR seems good, I'll test and merge it when I get home!

**Comment by bharadwajduggaraju** [comment]
@Borrus-sudo What this PR does is trying to do is great, but there seems to be a slight bug. Since the new Regex allows for expressions to span more than one line, the regex seems to think that two different expressions on different lines are the same expressions.

An example would be my markup being like this
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Test</title>
  </head>
  <body>
    {name}
    {name}
  </body>
</html>
```
The new regex is picking up both the {name}'s as one expression, like this "{name} {name}", since it allows the brackets to be more than one line.

If there is a way where we can limit the regex to only pickup one of them, that would be great

However, there is also the edge case of needing to used tag template literals in a evaluation like this 
```html
<div>{`${1+1}`}</div>
```
We dont want the regex to think that the {1+1} should be evaluated on its own or, have the regex pickup "{`${1+1}" as the expressions,

It there is any way to account for multiline brackets that would make sure these work, that would be great.

**Comment by bharadwajduggaraju** [comment]
However, I can merge in your other refactor, if you want to revert the regex changes, and submit a new version of them a new PR. Or you can just edit this one if you can solve the problem. It's up to you.

**Comment by Borrus-sudo** [comment]
Hey,
So I actually feel I may have a solution, I will test them and revert back

**Comment by Borrus-sudo** [comment]
Hey Bhardwaj,
Unfortunately I am unable to find the regex which handles every edge case, feel free to merge the previous change.

**Comment by bharadwajduggaraju** [comment]
Okay, I'll do that and change the Regex back, if you ever seem to figure out a solution, let me know - it could be really useful.

**Comment by Borrus-sudo** [comment]
Sure!

**Review by bharadwajduggaraju — APPROVED** [review]
approving - then going to change regex

**Pull request merged**
